"""Remove relationships

Revision ID: 6d20f2daf57c
Revises: 7e4c31694094
Create Date: 2025-03-28 17:54:42.293353

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d20f2daf57c"
down_revision: str | None = "7e4c31694094"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "categories", ["id"])
    op.create_unique_constraint(None, "products", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="unique")  # type: ignore[arg-type]
    op.drop_constraint(None, "categories", type_="unique")  # type: ignore[arg-type]
    # ### end Alembic commands ###
